Import('env commons_path bioinfo_path math_path')

#penv = env.Clone()

env.Program('hpg-var-vcf', 
             source = [Glob('*.c'), Glob('filter/*.c'), Glob('merge/*.c'), Glob('split/*.c'), Glob('stats/*.c'), Glob('../*.c'),
                       "%s/libcommon.a" % commons_path,
                       "%s/bioformats/libbioformats.a" % bioinfo_path
                      ]
           )
                      
env.Install('#bin', 'hpg-var-vcf')