Import('env commons_path bioinfo_path')

prog = env.Program('hpg-var-effect', 
             source = [Glob('*.c'), Glob('../*.c'),
                       "%s/libcommon.a" % commons_path,
                       "%s/bioformats/libbioformats.a" % bioinfo_path
                      ]
           )
 
Return("prog")
