Import('env  hpglib_path third_party_hts_path')

prog = env.Program('hpg-var-effect', 
             source = [Glob('*.c'), Glob('../*.c'),
                       "%s/build/libhpg.a" % hpglib_path,
                       "%s/libhts.a" % third_party_hts_path
                      ]
           )
 
Return("prog")
